### ISSUE TITLE
SPIKE: Editing Collection Metadata causing an error

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/atla_digital_library#154]
# Summary

This ticket has been turned into a spike ticket to investigate the error and what we may need to do to resolve it.  Create new ticket with enough acceptance criteria to point.  

I just edited the metadata for this collection - https://dl.atla.com/collections/baptistery-paintings-in-twentieth-century-churches-of-christ-by-blanche-garrett-perry, when i clicked save i got an error. It saved but showed this error.  

![Image](https://user-images.githubusercontent.com/29311858/202052191-11256c00-41bf-460d-b1ed-c6de4b1aa104.png)

Screenshot with URL

![Image](https://user-images.githubusercontent.com/29311858/202052210-f1cf9d10-a8b2-42e7-8ca7-0eaa3b78f636.png)

Metadata that was updated was the creator.  
If you refresh the page where you received the error you get the same error message, but cutting and pasting the URL into a new window shows the collection with the corrected metadata.  

# Acceptance Criteria

* [ ] We know the error and can add enough details that a ticket to resolve this can be pointed.  
* [ ] New ticket is created.

**Comment by DiemBTran** [comment]
Christy Jan 2022

---

Verified this is still happening as of 01/18/22

**Comment by DiemBTran** [comment]
April Jan 2022:

---

Confirming this on the dev side of production and linking the sentry issue for investigative purposes: https://sentry.notch8.com/sentry/atla/issues/138932/

Link to public view of the collection on production: https://dl.atla.com/collections/baptistery-paintings-in-twentieth-century-churches-of-christ-by-blanche-garrett-perry?locale=en

**Comment by labradford** [comment]
I can see from the URL in the address bar that the redirect went to the show page `/dashboard/collections/<collection-slug>?locale=en` and it should be going to the edit page `/dashboard/collections/<collection-slug>/edit?locale=en#description/`

**Comment by labradford** [comment]
Could not reproduce in dev, staging or production

**Comment by summer-cook** [comment]
Christy commented in slack that this issue is no longer happening:
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/73361970/231190334-69c93478-181e-402e-a599-645998981f93.png">

**Comment by labradford** [comment]
> Christy Karpinski
>   [6:41 AM](https://assaydepot.slack.com/archives/C031E2NF43T/p1681220462528419)
> [@Lea Ann Bradford](https://assaydepot.slack.com/team/U02T3KZD7BJ)
>  it does not seem to be happening anymore.
